### ISSUE TITLE
Tor timeout too short

### ISSUE THREAD

**Issue by MAWoodMain** [tachiniererin/nargh#1]
Hi, 
great project by the way,
I tried to run the script and ran into the issue of the TOR starting 1 minute timeout, on my system it seems to take around 2-3 mins, on my local copy I just set it to an hour for testing (not familiar with go so it was the simplest solution for me).

**Comment by tachiniererin** [comment]
I just pushed a change which ups the limit to 5 minutes. TOR shouldn't usually take very long to start, except if it's a really bad internet connection or maybe on really slow hardware.
I'd say if it takes longer than five minutes to start, something else is wrong somewhere else too ^^
